gcc fuse-example.c ../virtualFileSystem/hiredis/*.o ../virtualFileSystem/vfs.c ../virtualFileSystem/vfs_private.c \
 ../virtualFileSystem/vfsPathParser.c ../crypto.c ../utils.c ../net/networking.c ../net/connection.c ../httpProcessing/createHTTPHeader.c \
 ../google/googleAccessToken.c ../httpProcessing/realtimePacketParser.c ../fileTransfer.c ../google/googleDownloadDriver.c \
  -lssl -lcrypto -lfuse -D_FILE_OFFSET_BITS=64   -g -Wall
